### ISSUE TITLE
CRUD API for books section 

### ISSUE THREAD

**Issue by ali-7** [FACG5/tamer-project#10]
create endpoints for books section 

##### GET
- [x] /admin/books/library  #35 
- [x] /admin/books/store #38 
- [x] /admin/books/add #86
- [x] /admin/books/borrowed #41 
- [x] /admin/books/library/book/:libraryId #44 
- [x] /admin/books/store/book/:storeId #47 
- [x] /admin/books/library/book/edit/:libraryId #50 
- [x] /admin/books/store/book/edit/:storeId #56 
- [x] /admin/books/category #150 
- [x] /admin/books/category/edit/:categoryId #151 

##### POST
- [x] /admin/books #86
- [x] /admin/books/:bookId/library #62 
- [x] /admin/books/:bookId/store #65 
- [x] /admin/books/category #86

##### PUT
- [x] /admin/books/library/book/edit/:libraryId  #50 
- [x] /admin/books/store/book/edit/:storeId #56 
- [x] /admin/books/category/edit/:categoryId #151  

##### DELETE
- [x] /admin/books/library/:libraryId #53 
- [x] /admin/books/store/:storeId #59 
- [x] /admin/user/:userId #161 

relates to #8
