### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by lubnaabd** [FACG5/tamer-project#2]
## **As an admin**
- [x]  I can login to the admin panel.
- [x]  can logout from the admin panel.
- [x]  I can view dashboard statistics. 
- [x]  I can view the current books data in the library. 
- [x]  I can view the current books data in the store . 
- [x]  I can view the borrowed books data. 
- [x]  I can search for borrowed books.
- [x]  I can  search for book in the library.
- [x]  I can  search for book in the store.
- [x]  I can view book information in the library.
- [x]  I can view book information in the store.
- [x]  I can edit the current books data  in the library .
- [x]  I can delete the current books data  in the library .
- [x]  I can edit the current books data  in the store .
- [x]  I can delete the current books data  in the store .
- [x]  I can add new books.
- [x]  I can add new books in the library.
- [x] I can add new books in the store.
- [x]  I can view users.
- [x]  I can search for user.
- [x]  I can view borrowers.
- [x]  I can search for borrower.
- [x]  I can view the borrowing section.
- [x]  I can search for user by mobile number in the borrowing section.
- [x]  I can add new user when doesn't exists in the searching process.
- [x]  I can delete book to the user borrowing list.
- [x]  I can add book to the user borrowing list.
- [x]  If I go the wrong path  go the error page.

## **As a guest**
- [x]  I can search books tamer library.
- [x]  I can know from the result if the book available or not .
- [x]  I can view most borrowed books home page .
- [x]  If I go the wrong path  go the error page.
